### ISSUE TITLE
site takeover // DNS problems

### ISSUE THREAD

**Issue by justinthrelkeld** [finkhq/fink#31]
just a heads up: the domain xn--rn8h.ws is redirecting to another site. Looks like it might be a problem in the Cloudflare configuration.

**Comment by Kikobeats** [comment]
yes I'm investigating, with www works fine, right?

**Comment by Kikobeats** [comment]
also open a incognito chrome windows works fine, can you confirm me?

**Comment by Kikobeats** [comment]
I think that is a problem of browser cache, can you try flush browser cache?

**Comment by justinthrelkeld** [comment]
Cleared cache and it's now working fine, with www as well, yeah ✅ 

tested in Chrome, Chrome Incognito, Safari, Safari Tech Preview

**Comment by Kikobeats** [comment]
perfect, thanks for this! :smile:
