### ISSUE TITLE
URLs are broken when copied from Slack

### ISSUE THREAD

**Issue by FezVrasta** [finkhq/fink#67]
The symbols are copied as `:icon-description:` instead of the proper unicode symbol.

example:

`http://:rat:.ws/`

instead of

`http://🐀.ws/`

Can something be done to fix it? (I think no, because domains with colons are not allowed..)

**Comment by Kikobeats** [comment]
You're right, is not possible to fix. Too hipster project 😄 

You can use the fallback URL: http://xn--rn8h.ws/
