### ISSUE TITLE
The link for the website, beside the description is broken

### ISSUE THREAD

**Issue by kutyel** [finkhq/fink#9]
I guess its because is `https` instead of `http`, maybe you are planning to install the ssl but it made me difficult to find the correct url to the website xD btw: it works! http://🐀.ws/🌺

**Comment by Kikobeats** [comment]
I didn't find the https link, can you attach a screen or something?

**Comment by Kikobeats** [comment]
Ok link of the repo, facepalm. Fix it, thanks!

**Comment by kutyel** [comment]
You are welcome! :smile:
